Разбивка на компоненты
htmlacademy-vue/367335-pizza-1 pull request #2
Opened 2022-04-06 19:32 UTC by efiand

2022-04-06 19:42 UTC, efiand commented on src/frontend/src/assets/scss/app.scss
> -@import "mixins/mixins.scss";
Вынес в общую часть, чтобы вебпак добавлял всем компонентам. В app.scss оно попадет, так как app.scss импортирован в App.vue

2022-04-06 19:42 UTC, efiand commented on src/frontend/src/assets/scss/app.scss
> -@import "layout/header.scss";
Если я правильно понял, по итогу все блоки и лэйаут-стили должны переехать в SFC?

2022-04-06 19:42 UTC, efiand commented on src/frontend/src/modules/builder/components/BuilderPizzaView.vue
> +        for (let i = 1; i <= quantity; i++) {
В ТЗ как будто написано, что на каждый ингредиент нужен один div, но мне показалось логичным, что большее число ингредиентов должно визуально быть выражено через несколько дивов с разным углом поворота, поэтому так и сделал. К тому же старый добрый цикл избавил от необходимости лишний раз фильтровать ингредиенты на предмет ненулевого количества.

2022-04-06 19:42 UTC, efiand commented on src/frontend/src/modules/builder/components/BuilderPizzaView.vue
> +  &--size--small {
Отсебятина (кажется, что изменение размера тоже должно визуально отражаться). Если это грубое нарушение ТЗ, то уберу. На реальной работе пошел бы с подобным предложением к аналитику, если бы в ТЗ оно отсутствовало.

2022-04-10 23:46 UTC, wspwebben requested changes

2022-04-10 23:46 UTC, wspwebben commented on src/frontend/src/common/components/AppDrop.vue
> +    className: {
Во вью классы и стили автоматически проваливаются на корневой элемент, поэтому вместо передачи пропса лучше писать `<AppDrop class="some-class" />`

[docs](https://ru.vuejs.org/v2/guide/class-and-style.html#%D0%98%D1%81%D0%BF%D0%BE%D0%BB%D1%8C%D0%B7%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5-%D1%81-%D0%BA%D0%BE%D0%BC%D0%BF%D0%BE%D0%BD%D0%B5%D0%BD%D1%82%D0%B0%D0%BC%D0%B8)

2022-04-10 23:46 UTC, wspwebben commented on src/frontend/src/common/components/ItemCounter.vue
> +        const newValue = Math.min(Math.max(value, 0) || 0, this.max);
Не очень понял зачем здесь `|| 0`

2022-04-10 23:46 UTC, wspwebben commented on src/frontend/src/common/components/RadioButton.vue
> +    <span v-else>{{ label }}</span>
Не заметил разницы между стилями `<b>` и `<span>`, мы можем упростить шаблон, если будем использовать один тег в обоих случаях

2022-04-10 23:46 UTC, wspwebben commented on src/frontend/src/common/utils.js
> +}
Хорошее решение с множителями 👍

2022-04-10 23:46 UTC, wspwebben commented on src/frontend/src/common/utils.js
> +}
Лично я не очень большой фанат держать значения инпутов в объектах, которые описывают их отображение, но комьюнити по этому вопросу разделилось, поэтому не буду настаивать на каком-то варианте, просто опишу почему мне больше нравится держать состояние отдельно:

- простые структуры лучше работают с v-model
- не нужно пересобирать все данные, чтобы поменять одно значение
- лучше видно какие данные являются состоянием, а какие просто статика

2022-04-10 23:46 UTC, wspwebben commented on src/frontend/src/layouts/AppLayoutHeader.vue
> +      <a class="logo" href="index.html">
Я бы рекомендовал разбивать компоненты на максимально мелкие части, один из маркеров, что мы можем подробить еще сильнее - несколько блоков в одном компоненте

Если мы вынесем компонент лого, мы сможем хранить шаблон и стили в одном месте, что упростит дальнейшую работу

2022-04-10 23:46 UTC, wspwebben commented on src/frontend/src/modules/builder/components/BuilderDoughSelector.vue
> +      :key="`dough-${item.id}`"
У нас в нескольких местах используется подобный код, было бы здорово вынести вывод списка радиокнопок в отдельный компонент

2022-04-10 23:46 UTC, wspwebben commented on src/frontend/src/modules/builder/components/BuilderPizzaView.vue
> +        for (let i = 1; i <= quantity; i++) {
Хорошая идея, выглядит здраво 👍 

А вот цикл выглядит немного не по-вьюшному: я бы вынес вывод ингредиентов в отдельный компонент, который уже бы разруливал все повороты по количеству ингредиентов
Сейчас код слишком императивный

2022-04-10 23:46 UTC, wspwebben commented on src/frontend/src/modules/builder/components/BuilderPizzaView.vue
> +  &--size--small {
По-моему разумное предложение, я бы оставил

2022-04-10 23:46 UTC, wspwebben commented on src/frontend/src/modules/builder/components/BuilderPizzaView.vue
> +  name: "BuilderPizzaView",
Давай оставим суффикс -View только у компонентов роутера

2022-04-10 23:46 UTC, wspwebben commented on src/frontend/src/views/IndexView.vue
> +              @change="currentPizza.dough = $event"
Во вью есть очень мощный и выразительный механизм двустороннего связывания - `v-model`
Он лучше отражает то, что происходит в коде

Я бы предложил использовать его, но не со стандартной парой пропс/событие (`value/input`), а переопределить на более осмысленные, например, `dough/update:dough` - во вью 2 такой синтаксис используется для модификатора .sync, но во вью3 это новый стандарт для v-model, поэтому лучше ориентироваться на него

[Модификатор sync](https://ru.vuejs.org/v2/guide/components-custom-events.html#%D0%9C%D0%BE%D0%B4%D0%B8%D1%84%D0%B8%D0%BA%D0%B0%D1%82%D0%BE%D1%80-sync)
[Настройка v-model](https://ru.vuejs.org/v2/guide/components-custom-events.html#%D0%9D%D0%B0%D1%81%D1%82%D1%80%D0%BE%D0%B9%D0%BA%D0%B0-v-model-%D1%83-%D0%BA%D0%BE%D0%BC%D0%BF%D0%BE%D0%BD%D0%B5%D0%BD%D1%82%D0%B0)

2022-04-10 23:46 UTC, wspwebben commented on src/frontend/src/views/IndexView.vue
> +              @changeIngredients="currentPizza.ingredients = $event"
Так как у этого компонента 2 значения, мы не можем использовать v-model (потому что во вью 2 он только один), так что это был бы хороший пример для .sync

Однако есть более простое решение: сделать 2 независимых поля формы, одно из которых отвечает за выбор соусов, второе - за ингредиенты

2022-04-10 23:46 UTC, wspwebben commented on src/frontend/src/views/IndexView.vue
> +            />
Базовые компоненты как инпут или кнопка можно по умолчанию выносить в отдельные компоненты, тем более это один из примеров правила "1 компонент - 1 бэм блок"

2022-04-10 23:46 UTC, wspwebben commented on src/frontend/src/views/IndexView.vue
> +            </button>
Кнопка, как и инпут, базовый элемент интерфейса, его можно выносить в самостоятельный компонент, не задумываясь

2022-04-10 23:46 UTC, wspwebben commented on src/frontend/src/views/IndexView.vue
> +const initialPizza = {
Я бы заменил этот объект на фабрику, которая всегда создаст новый объект, чтобы мы даже при желании не могли накосячить с ссылками

2022-04-10 23:46 UTC, wspwebben commented on src/frontend/src/views/IndexView.vue
> +      currentPizza: cloneDeep(initialPizza),
Здесь получится `currentPizza: createPizza()`

2022-04-22 08:11 UTC, efiand commented on src/frontend/src/layouts/AppLayoutHeader.vue
> +      <a class="logo" href="index.html">
Это касается и компонентов типа `<Title class="sheet__title" small>Выберите тесто</Title>`?

2022-04-22 09:10 UTC, efiand commented on src/frontend/src/common/components/ItemCounter.vue
> +        const newValue = Math.min(Math.max(value, 0) || 0, this.max);
Если в поле ввести не число, без этой записи будет так:
![изображение](https://user-images.githubusercontent.com/26799424/164675134-d6d8cddb-b9e2-44f9-8915-499b4d51239c.png)

Значение truthy, но результат Math.max будет NaN, поэтому я и добавил ` || 0`. Не знаю, как лучше решить эту проблему.

2022-04-22 09:18 UTC, wspwebben commented on src/frontend/src/layouts/AppLayoutHeader.vue
> +      <a class="logo" href="index.html">
Да, если элемент самодостаточный, стоит выносить его в компонент, даже если это всего один тег

2022-04-22 09:46 UTC, efiand commented on src/frontend/src/common/components/RadioButton.vue
> +    <span v-else>{{ label }}</span>
Проблема в том, что верстальщик сделал одинаковые вещи неодинаково (я бы сверстал все три радиобаттона однообразными классами, оставив различие только в типах буллета) - в одном компоненте спан отвечает за название, в другом за описание (и там `<b>` за название). Я решил выкрутиться тем, что поменял span на small там, где описание.

2022-04-22 10:04 UTC, efiand commented on src/frontend/src/layouts/AppLayoutHeader.vue
> +      <a class="logo" href="index.html">
Спасибо. Так и сделаю.

2022-04-22 14:23 UTC, wspwebben commented on src/frontend/src/common/components/RadioButton.vue
> +    <span v-else>{{ label }}</span>
Верстка это просто начальная точка, если она не очень хорошо ложится на компоненты, которые мы выделили, ее смело можно и нужно менять

2022-04-23 20:40 UTC, efiand commented on src/frontend/src/common/components/RadioButton.vue
> +    <span v-else>{{ label }}</span>
Ура! С удовольствием учту )

2022-04-23 20:42 UTC, efiand commented on src/frontend/src/common/utils.js
> +}
Переосмыслил решение: теперь радиобаттон получает примитив

2022-04-23 21:07 UTC, efiand commented on src/frontend/src/modules/builder/components/BuilderDoughSelector.vue
> +      :key="`dough-${item.id}`"
Попробовал сделать компонент списка радиокнопок - не получилось оптимизации, в итоге вышло, что в нескольких местах стал использоваться список ) а вложенность возросла.
В общем, пользуясь разрешением модифицировать верстку, унифицировал радиобаттоны насколько возможно. А также унифицировал контентные блоки с подзаголовками

2022-04-23 21:08 UTC, efiand commented on src/frontend/src/views/IndexView.vue
> +            />
Так и поступил.

2022-04-23 21:09 UTC, efiand commented on src/frontend/src/views/IndexView.vue
> +              @changeIngredients="currentPizza.ingredients = $event"
Выделил ингредиенты в отдельный компонент

2022-04-23 21:26 UTC, efiand commented on src/frontend/src/views/IndexView.vue
> +              @change="currentPizza.dough = $event"
В текущем варианте не понял, как применить v-model, с учетом того, что радиобаттоны унифицировал, и эта прослойка BuilderDoughSelector оказалась как будто не очень нужной.

2022-04-24 13:37 UTC, wspwebben requested changes

2022-04-24 13:37 UTC, wspwebben commented on src/frontend/src/modules/builder/components/BuilderPizza.vue
> +      this.pizza.ingredients[ingredient]++;
Здесь мутируется исходный пропс, так как объекты передаются по ссылке, это очень грубое нарушение потока данных

2022-04-24 13:37 UTC, wspwebben commented on src/frontend/src/modules/builder/components/BuilderPizza.vue
> +      this.$emit("change", this.pizza.ingredients);
Хорошее правило работы с элементами форм: данные, которые мы передаем в компонент должны иметь ту же структуру, что и те, которые мы передаем наверх, чтобы сверху условная запись `@change="value = $event"` была корректной

В этом случае нужно либо обновить пропсы так, чтобы компонент принимал только ингредиенты, а не весь объект пиццы, либо эмитить весь обновленный объект целиком (копию, не мутировать старый!)

Так как здесь поля кроме `ingredients` используются только в формировании класса, но не в логике самого компонента, я бы предпочел первый вариант, а формирование класса либо вынес в родителя либо передавал отдельными пропсами

2022-04-24 13:37 UTC, wspwebben commented on src/frontend/src/common/components/BlockButton.vue
> +    {{ title }}
Здесь слот подойдет лучше, это позволит сделать использование кнопок более похожим на обычные хтмл элемент:

```
<button>Ok</button>
<BlockButton>Ok</button>
```

2022-04-24 13:37 UTC, wspwebben commented on src/frontend/src/common/components/BlockButton.vue
> +  <button class="button" :type="type" :disabled="disabled" v-on="$listeners">
Я считаю прокидывание $listeners плохой практикой, так как прописывание эмитов явно указывает контракт кнопки, а, учитывая что нам обычно нужен только `click`, такая запись особо не сокращает количество кода

2022-04-24 13:37 UTC, wspwebben commented on src/frontend/src/common/components/BlockInput.vue
> +      @input="$emit('change', $event.target.value)"
Я бы рекомендовал использовать v-model везде, где мы работаем с инпутами, так как он лучше выражает семантику, которую мы вкладываем - обновление значения
Компьютед с сеттером, который ты уже использовал, позволяет это делать, не мутируя значение, а также немного абстрагирует нас от дом элемента, так как вью сам распакует `.target.value` при передаче значения в сеттер

```
computed: {
    value: {
      get() {
        return this.value;
      },
      set(value) {
        this.$emit("input", value);
      },
    },
  },
```

2022-04-24 13:37 UTC, wspwebben commented on src/frontend/src/common/utils.js
> +  return isNaN(number) || number < 0 ? 0 : number;
Сейчас код очень сильно полагается на приоритет операторов, пожалуйста, поставь скобки, чтобы обозначить его более явно

2022-04-24 13:37 UTC, wspwebben commented on src/frontend/src/modules/builder/components/BuilderFillingSelector.vue
> +      this.value[alias] = quantity;
Тут мутируется пропс :(

2022-04-24 13:37 UTC, wspwebben commented on src/frontend/src/modules/builder/components/BuilderFillingSelector.vue
> +      this.$emit("change", this.value);
Самый простой способ добавить поддержку v-model: переименовать событие в `input` - это стандартное имя события для кастомных компонентов

Если хочется оставить `change`, можно дописать в компонент такой код:

```
export default {
  model: {
    prop: 'value',
    event: 'change',
  } ,
}
```

2022-04-24 13:41 UTC, wspwebben commented
Отлично, по разбивке компонентов у меня, пожалуй, больше нет вопросов, все хорошо исправлено 👍 

У меня остались только замечания к работе с потоком данных - это в основном мутации пропсов или отстутствие v-model там, где есть явно выраженная семантика двустороннего связывания

2022-04-27 08:37 UTC, efiand commented on src/frontend/src/modules/builder/components/BuilderPizza.vue
> +      this.$emit("change", this.pizza.ingredients);
Мне кажется, что логика навешивания классов должна быть в данном случае инкапсулирована в компоненте (вообще показалось логичным для сознания БЭМ-классы блоков и элементов вешать внутри компонента, а БЭМ-миксы классов БЭМ-элементов - снаружи).

Переделал на отдельные пропсы, и так как я передаю весь объект ингредиентов, то решил эмитить клон объекта ингредиентов, только вопрос: если я заранее знаю, что объект этот из примитивов, можно не использовать cloneDeep, а сделать так?

![изображение](https://user-images.githubusercontent.com/26799424/165477651-1e0be6f1-21cf-4c22-bffd-68c19de4ad7b.png)

2022-04-27 14:12 UTC, efiand commented on src/frontend/src/modules/builder/components/BuilderPizza.vue
> +      this.$emit("change", this.pizza.ingredients);
Еще возникла мысль о таком решении (оба способа в сравнении, второй зеленым):
![изображение](https://user-images.githubusercontent.com/26799424/165538183-dcf59c1b-be10-4d72-ae9c-1d187a7e85d9.png)

Но это, как я понимаю, нарушает принцип
> данные, которые мы передаем в компонент должны иметь ту же структуру, что и те, которые мы передаем наверх

2022-04-27 14:16 UTC, efiand commented on src/frontend/src/common/components/BlockButton.vue
> +    {{ title }}
По идее, в BlockHeading и BlockSubheading можно так сделать?

2022-04-27 14:33 UTC, efiand commented on src/frontend/src/common/utils.js
> +  return isNaN(number) || number < 0 ? 0 : number;
prettier под вебпаком бросает варнинги, но я согласен, что со скобками читаемость лучше.
Наверное, стоит сделать так:

```js
export function getPositiveIntFromValue(value) {
  const number = parseInt(value, 10);
  const notPositive = isNaN(number) || number < 0;
  return notPositive ? 0 : number;
}
```

2022-04-27 14:36 UTC, efiand commented on src/frontend/src/modules/builder/components/BuilderFillingSelector.vue
> +      this.value[alias] = quantity;
Второй случай (( когда мутировались примитивы, в консоли писалось, а тут не заметил

2022-04-27 15:07 UTC, wspwebben commented on src/frontend/src/modules/builder/components/BuilderPizza.vue
> +      this.$emit("change", this.pizza.ingredients);
да, на самом деле

2022-04-27 15:08 UTC, wspwebben commented on src/frontend/src/modules/builder/components/BuilderPizza.vue
> +      this.$emit("change", this.pizza.ingredients);
Да, cloneDeep вообще далеко не всегда нужен
Даже если внутри не примитивы, но мы не меняем их, то даже лучше сохранить ссылки на старые объекты

2022-04-27 15:13 UTC, wspwebben commented on src/frontend/src/common/components/BlockButton.vue
> +    {{ title }}
Верно, они тоже похожи на h1/h2/h3, поэтому слоты для них более подходящий вариант

Важно отметить, что это не значит, что передавать текст пропсом будет ошибкой, например, может быть такая структура:

```
<FormGroup title="Адрес">
  <Field label="Страна" />
  <Field label="Город" />
</FormGroup>
```

а внутри `FormGroup` уже используется слот
```
<div>
  <FormTitle>{{ title }}</FormTitle>
</div>
```

2022-04-27 15:14 UTC, wspwebben commented on src/frontend/src/common/components/BlockButton.vue
> +    {{ title }}
пример выше можно переписать на слоты, но это будет выглядеть чуть хуже (на мой взгляд)

```
<FormGroup>
  <template #title>Адрес</template>

  <Field label="Страна" />
  <Field label="Город" />
</FormGroup>
```

2022-04-27 15:16 UTC, wspwebben commented on src/frontend/src/common/components/BlockButton.vue
> +    {{ title }}
Так что тут нет единственно верного решения, нужно представить как ты будешь использовать этот компонент, и какой из вариантов выглядит более удобно

Например, если мы хотим иметь возможность добавить в кнопку икноку, то со слотами это будет сделать намного проще

2022-04-27 15:17 UTC, efiand commented on src/frontend/src/common/components/BlockButton.vue
> +    {{ title }}
Да, что-то читается хуже.

> а внутри FormGroup уже используется слот

BlockSheet сейчас так себя и ведет

2022-04-27 16:06 UTC, efiand commented on src/frontend/src/common/components/BlockInput.vue
> +      @input="$emit('change', $event.target.value)"
Применил. Только с радиобаттонами никак: checked-атрибут убивается, на котором стили построены.

2022-04-28 16:10 UTC, wspwebben commented on src/frontend/src/modules/builder/components/BuilderPizza.vue
> +  },
Не понял зачем этот блок нужен, даже не вижу, что он где-то используется

2022-04-28 16:11 UTC, wspwebben commented
Кроме вопроса про блок с `mutableIngredients` у меня больше нет замечаний 👍

2022-04-28 22:14 UTC, efiand commented on src/frontend/src/modules/builder/components/BuilderPizza.vue
> +  },
Это я случайно недооткатывал промежуточную реализацию (

2022-04-29 17:34 UTC, merged