Module4 task1
htmlacademy-vue/367335-pizza-1 pull request #4
Opened 2022-06-04 14:15 UTC by efiand

Пытался осмыслить то, что не надо заменять все пропсы на хранилище. Показалось разумным ограничить работу с хранилищем корзины и заказов на уровне вьюх, чтобы не тянуть через цепочку лэйаутов (а пользователя на уровне лэйаута). Для билдера показалось правильным не делать стор, так как там все это в пределах лишь одной страницы и уже разделено по ответственности между компонентами.
Также, помня о неоднозначности миксинов и том, что у меня там какая-то нездоровая конструкция с ценами получилась, решил вынести логику формирования и отображения цены в отдельный компонент (найдя решение, как унифицировать вывод цены за пиццу и стоимости всего заказа).

P.S. Старался осмысленно поделить на коммиты, но не удалось выделить компонент цены в отдельный коммит, так как уже много всего было намешано, творческий процесс шел стихийно.

2022-06-07 13:15 UTC, wspwebben requested changes

2022-06-07 13:15 UTC, wspwebben commented on src/frontend/src/store/modules/auth.js
> +    currentUser: {},
тут больше подойдет null

2022-06-07 13:15 UTC, wspwebben commented on src/frontend/src/store/modules/cart.js
> +      currentOrder.pizzas[index] = {
во вьюксе действуют такие же правила реактивности, как и в компонентах, т.е. обновление по индексу не реактивно

нужно использовать Vue.set или пересобрать весь массив с помощью .map

2022-06-07 13:15 UTC, wspwebben commented on src/frontend/src/store/modules/cart.js
> +    [ADD_PIZZA]({ currentOrder }, pizza) {
стейт лучше не деструктурировать, чтобы переменная всегда ссылалась на правильную ссылку

2022-06-07 13:15 UTC, wspwebben commented on src/frontend/src/store/modules/orders.js
> +      orders.splice(orders.indexOf(order), 1);
что будет, если переданного элемента не окажется в массиве?

2022-06-07 13:58 UTC, efiand commented on src/frontend/src/store/modules/auth.js
> +    currentUser: {},
А как тогда лучше сделать при передаче через пропс? Там сейчас обязательный объект ждет.

2022-06-07 15:01 UTC, efiand commented on src/frontend/src/store/modules/orders.js
> +      orders.splice(orders.indexOf(order), 1);
Беда будет ((
чет не сообразил, все проверки шли из интерфейса, где наличие кнопки удаления собственно наличием элемента и обусловлено.

2022-06-08 11:42 UTC, wspwebben commented on src/frontend/src/store/modules/auth.js
> +    currentUser: {},
нет, default срабатывает только для undefined

мне в целом не очень нравится идея использовать пустой объект в качестве пользователя, потому что при сравнении он тоже будет истинным

2022-06-08 11:44 UTC, wspwebben commented
👍

2022-06-08 11:45 UTC, efiand commented on src/frontend/src/store/modules/auth.js
> +    currentUser: {},
В общем, когда я делаю currentUser: null, выскакивает ошибка, что пришел неверный тип пропса. А если при этом required заменить на default, то такой ошибки нет. То есть, дело было не в том, что я добавил default, а в том, что убрал required?

2022-06-08 11:48 UTC, wspwebben requested changes

2022-06-08 11:48 UTC, wspwebben commented on src/frontend/src/layouts/AppLayoutHeader.vue
> +      default: () => ({}),
если не передать поле, то мы получим пустой объект, которые пройдет проверку в v-if, но полей для вывода у него не будет

сейчас в этом случае мы просто ничего не выведем, кроме лишней верстки, но если добавятся вложенные поля, то при попытке получить какой-нибудь `user.image.small`, то мы упадем с ошибкой

2022-06-08 12:07 UTC, efiand commented on src/frontend/src/layouts/AppLayoutHeader.vue
> +      default: () => ({}),
Если убрать эту проверку, то все работает. Проблема начинается, если вернуть `required: true` - `Invalid prop: type check failed for prop "user". Expected Object, got Null `. Как же быть: в данном случае достаточно только указать тип, или надо написать кастомный валидатор?

2022-06-08 13:08 UTC, merged

2022-06-08 14:18 UTC, wspwebben commented on src/frontend/src/layouts/AppLayoutHeader.vue
> +      default: () => ({}),
нужно указать, что в пропсе может быть 2 типа: `type: [Object, null]`

2022-06-08 14:28 UTC, efiand commented on src/frontend/src/layouts/AppLayoutHeader.vue
> +      default: () => ({}),
Спасибо! Это я упустил по программе. Поправлю.

2022-06-10 09:08 UTC, efiand commented on src/frontend/src/layouts/AppLayoutHeader.vue
> +      default: () => ({}),
![изображение](https://user-images.githubusercontent.com/26799424/173032180-c6ce5543-fba8-480a-a1f0-0bb7f42a9af9.png)
![изображение](https://user-images.githubusercontent.com/26799424/173032230-094ccffa-eb40-41e1-94a6-547e549a6de8.png)

2022-06-10 11:36 UTC, wspwebben commented on src/frontend/src/layouts/AppLayoutHeader.vue
> +      default: () => ({}),
Да, я ошибся: null и undefined в типе указывать нельзя
Оба твоих предложения выше: убрать required или написать валидатор подходят

2022-06-10 16:09 UTC, efiand commented on src/frontend/src/layouts/AppLayoutHeader.vue
> +      default: () => ({}),
А `default: null` нам подойдет в таком случае вместо валидатора? Я проверил, ошибки в программе нет.

2022-06-12 15:48 UTC, wspwebben commented on src/frontend/src/layouts/AppLayoutHeader.vue
> +      default: () => ({}),
Да, `default: null` будет лучшим вариантом на мой взгляд, я его в другом комменте и предлагал

2022-06-12 15:50 UTC, efiand commented on src/frontend/src/layouts/AppLayoutHeader.vue
> +      default: () => ({}),
Спасибо! Видимо, я его как-то неправильно осознал.