Module5 task1
htmlacademy-vue/367335-pizza-1 pull request #5
Opened 2022-06-17 16:42 UTC by efiand

Постарался разделить на коммиты, но не получилось (в процессе решил отрефакторить половину проекта, так как с адаптерами бы запутался больше, чем с переделкой мод модель данных API. В итоге стали не нужны некоторые методы и даже избавился от миксинов).
Позже переклеил коммиты более-менее тематически.
С мидлварами, возможно, что-то не до конца понял, но как будто бы тут можно обойтись без них, не инициализируя лэйаут с сайдбаром при отсутствии данных о пользователе.
Много времени убил на то, что при лишних данных в теле отправки заказа запись создается, но гнутая: списки пицц и ингредиентов undefined. Ожидал, что если ошибка 422, то запись вообще не создастся (когда повторяешь заказ из профайла, там id оставались, поэтому я сделал мегаадаптер на этапе получения данных, чтобы подстроиться под структуру данных корзины).

2022-06-21 20:28 UTC, wspwebben requested changes

2022-06-21 20:28 UTC, wspwebben commented on src/frontend/src/common/components/AppNotifications.vue
> +      :key="i"
Индекс это плохой ключ для данных, которые будут меняться

2022-06-21 20:28 UTC, wspwebben commented on src/frontend/src/common/helpers.js
> +  contentEntity.forEach((contentItem) => {
Ты написал собственный .map

2022-06-21 20:28 UTC, wspwebben commented on src/frontend/src/common/helpers.js
> +  return userData;
Зачем эти функции мутируют исходный объект? Почему не вернуть новый?

2022-06-21 20:28 UTC, wspwebben commented on src/frontend/src/plugins/ui.js
> +Vue.component("AppNotifications", AppNotifications);
Этот компонент используется только в одном месте, зачем объявлять его глобально?

2022-06-21 20:28 UTC, wspwebben commented on src/frontend/src/plugins/vue-plugins.js
> +          return createResources(this.$notifier);
Эти компьютеды будут высчитываться для каждого компонента и создавать инстансы на каждый компонент

Лучшим (насколько это возможно при поставленной задаче) будет записать их в прототип (4 пункт https://ru.vuejs.org/v2/guide/plugins.html)

2022-06-21 20:28 UTC, wspwebben commented on src/frontend/src/plugins/vue-plugins.js
> +          return createResources(this.$notifier);
Если же говорить без оглядки на задание курса, глобальных зависимостей лучше избегать

Например, апи проще просто импортировать как обычные функции (или экземпляр класса, если так больше нравится) в те места, где они вызываются вместо того, чтобы тянуться в `this.$api`

2022-06-21 23:11 UTC, efiand commented on src/frontend/src/common/components/AppNotifications.vue
> +      :key="i"
Точно, у них же id есть

2022-06-21 23:19 UTC, efiand commented on src/frontend/src/common/helpers.js
> +  contentEntity.forEach((contentItem) => {
Вроде и похоже, но мне требуется избавиться от серверных дублей, ведь ни верстка толком под них не приспособлена, ни вообще здравый смысл их не предполагает. И тут придется если только пробегать потом еще раз методом `.filter`, ведь мэп вернет то же число элементов.

2022-06-21 23:55 UTC, efiand commented
Исправил всё, кроме импортирования API как обычных функций (но на будущее учёл: мне тоже так больше нравится, думаю, раз показали в материалах, значит, `vue way`), и кроме "велосипедного" мэпа, который не совсем мэп, и другого решения придумать не удалось.

2022-06-22 08:34 UTC, wspwebben commented on src/frontend/src/common/helpers.js
> +  contentEntity.forEach((contentItem) => {
Согласен, слишком бегло прочитал функцию

Я бы оставил `.map().filter()`, потому что это более выразительно, а размер массивов не настолько большой, чтобы это было критично

Но вариант с одним проходом тоже можно оставить, но тогда лучше заменить `.forEach` на `for of`: это опять же более выразительно передает императивность кода

Лично я вообще не очень люблю использовать .forEach, потому что, как по мне, варианты выше делают тоже самое, но лучше

2022-06-22 08:39 UTC, wspwebben commented
С `vue way` есть небольшая проблема: очень много вещей можно сделать разными способами, а документация имеет мнение далеко не по всем вопросам, а раньше вообще продвигала спорные решения

В том, что касается импортов, я бы рекомендовал опираться на старый добрый принцип "явное лучше неявного"

Про цикл отписался в комменте, но это не блокирующее пожелание 👍

2022-06-22 08:39 UTC, merged

2022-06-22 08:57 UTC, efiand commented on src/frontend/src/common/helpers.js
> +  contentEntity.forEach((contentItem) => {
Я думал о `map().filter(Boolean)`, но тут тоже загвоздка: в третьем параметре коллбэка я получал старый массив, а мне надо проверять, нет ли на данный момент дубля по отношению к только что накопленным в новом массиве элементам. То есть получается, что другого варианта не придумалось. `for of` я тоже люблю, но помню критерии интенсива по JS, где требовалось единообразие. Тут в критериях этого нет, так что переделаю.

2022-06-22 09:01 UTC, efiand commented
Спасибо!
Да, принцип "явное лучше неявного" как-то больше заходит. Те же миксины что на работе было трудно поддерживать, что в учебном проекте начал путаться, с плагинами вот тоже было трудно сообразить, как всё взаимосвязано и главное зачем.