Module7 task1
htmlacademy-vue/367335-pizza-1 pull request #7
Opened 2022-07-04 21:07 UTC by efiand

2022-07-07 13:54 UTC, wspwebben requested changes

2022-07-07 13:54 UTC, wspwebben commented on src/frontend/src/common/components/__tests__/BlockButton.spec.js
> +    expect(listeners.click).toHaveBeenCalled();
В других компонентах мы тестировали события через поле emitted, лучше везде использовать один подход

2022-07-07 13:54 UTC, wspwebben commented on src/frontend/src/common/components/__tests__/BlockButton.spec.js
> +    expect(wrapper.attributes("type")).toBe(defaultBtnType);
Можно упростить этот тест, записав его в табличном синтаксисе:

```
it.each(['button', 'submit'])("uses passed button type", (type) => {
    createComponent({
      propsData: {
        type,
      },
    });

    expect(wrapper.attributes("type")).toBe(type);
})
```

2022-07-07 13:54 UTC, wspwebben commented on src/frontend/src/layouts/__tests__/AppLayoutDefault.spec.js
> +  });
Почему эти два теста проверяют похожие кейсы, но проверки выглядят по-разному?

2022-07-07 13:54 UTC, wspwebben commented on src/frontend/src/common/components/__tests__/BlockCounter.spec.js
> +    expect(wrapper.emitted().input[0][0]).toEqual(propsData.max);
Мне больше нравится не ссылатся на дефолтные пропсы в тестах, а прописывать их явно, чтобы было видно какие значения используются в кейсе

2022-07-07 13:54 UTC, wspwebben commented on src/frontend/src/common/components/__tests__/BlockCounter.spec.js
> +    expect(buttonWrapper.classes()).toContain(secondaryClassName);
Еще один вариант вместо табличных тестов: создавать компонент без пропса и в этом же тесте его менять, проверяя что его не было, и он появился

2022-07-07 13:54 UTC, wspwebben commented on src/frontend/src/layouts/__tests__/AppLayoutHeader.spec.js
> +const localVue = createLocalVue();
Насколько я помню, джест автоматически очищает зависимости между файлами теста, поэтому создавать localVue нет необходимости, а сама операция довольно дорогая

2022-07-07 13:54 UTC, wspwebben commented on src/frontend/src/layouts/__tests__/AppLayoutHeader.spec.js
> +    wrapper.destroy();
Можно включить автоматическое удаление врапперов, указав в конфиге джеста поле
`setupFilesAfterEnv: ['<rootDir>/jest.setup.ts'],`

И в этом файле прописать такую настройку
```
import { enableAutoDestroy } from '@vue/test-utils'

enableAutoDestroy(global.afterEach)
```

2022-07-07 15:28 UTC, efiand commented on src/frontend/src/common/components/__tests__/BlockButton.spec.js
> +    expect(listeners.click).toHaveBeenCalled();
Это я сначала как из одного примера учебника делал, потом как из другого ( в конце уже забыв про listeners. Получается, без них можно вообще обойтись?

2022-07-07 15:29 UTC, efiand commented on src/frontend/src/common/components/__tests__/BlockButton.spec.js
> +    expect(wrapper.attributes("type")).toBe(defaultBtnType);
Круто! А я в конце уже начал костылять через обычный `.forEach`. Я бы и тут сделал, но не заметил идентичности тестов.

2022-07-07 15:48 UTC, efiand commented on src/frontend/src/common/components/__tests__/BlockCounter.spec.js
> +    expect(wrapper.emitted().input[0][0]).toEqual(propsData.max);
Ты имеешь в виду, что `propsData` в каждом it передавать явным образом?

2022-07-08 08:56 UTC, wspwebben commented on src/frontend/src/common/components/__tests__/BlockCounter.spec.js
> +    expect(wrapper.emitted().input[0][0]).toEqual(propsData.max);
У меня тесты выглядят вот так: есть дефолтные пропсы, но если тест использует их, то я все равно передаю их

<img width="722" alt="image" src="https://user-images.githubusercontent.com/34203719/177956154-d16397ed-c61d-418e-9e4a-1fa61307281c.png">
<img width="556" alt="image" src="https://user-images.githubusercontent.com/34203719/177956192-f8e413da-9607-4e3e-b631-fdbe13cdd67a.png">

2022-07-08 11:02 UTC, efiand commented on src/frontend/src/layouts/__tests__/AppLayoutHeader.spec.js
> +const localVue = createLocalVue();
Действительно, без этого всё работает. Правда, на скорости выполнения не выражается.

2022-07-08 11:03 UTC, efiand commented
Остались пустые папки или папки с пустыми индексными файлами, и вообще пустые индексные файлы. Правильно ли будет их удалить?

2022-07-11 08:20 UTC, wspwebben commented
Да, я бы удалил
Папки все равно гит не трекает, да и в целом лишние и бесполезные файлы лучше не оставлять, всегда проще добавить их заново

2022-07-11 08:21 UTC, wspwebben commented
Выполнение задания это не блокирует, поэтому этот пр принимаю 👍

2022-07-11 08:21 UTC, merged